notifications:
  email: false
language: java

sudo: false
addons:
  apt:
    packages:
      - oracle-java8-installer

# command to build
install:
  - "gradle assemble"

# command to run tests
script:
  - "gradle check"

after_success: